### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by jaymoulin** [KingCrunch/CacheControl#3]
Everthing was working great but I just has thing strange error : 

```
/home/myproject/vendor/bin/cache-control clear --host /var/run/myproject.socket
PHP Warning:  Invalid argument supplied for foreach() in /home/myproject/vendor/crunch/cache-control/src/Console/ClearCommand.php on line 20
```

Current version is 0.2.2 even if `/home/myproject/vendor/bin/cache-control --version` says `Console Tool`

**Comment by jaymoulin** [comment]
Projects unmaintained

**Comment by lyrixx** [comment]
@jaymoulin See this other project https://github.com/gordalina/cachetool ;)
